### ISSUE TITLE
What dataPin = 3 in ESP8266 ?

### ISSUE THREAD

**Issue by tinamore** [dmarkey/smarthome_esp8266controller_sming#2]
Hi
## I don't know PIN 3 in ESP8266-01 (has only GPIO 0 and GPIO 0 ?) ?
# ifdef FOUR_SWITCH_MODE

```
const int latchPin = 0;
//Pin connected to clock pin (SH_CP) of 74HC595
const int clockPin = 2;
////Pin connected to Data in (DS) of 74HC595
const int dataPin = 3;
```
# endif

---

Thanks :)

**Comment by dmarkey** [comment]
3 is the Data pin for the shift register. The UART pins on the ESP-01 can also be used for GPIO.
